### PR TITLE
Migrate entire project to Swift 5

### PR DESCRIPTION
**Pull request by wjk**
Does what the title says. Note that after this migration, I am seeing a number of warnings like this one:

```
'withUnsafeBytes' is deprecated: use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead
```

I have not fixed these yet because I have not yet been able to ensure I have found the correct fix for the warnings. (The only difference between these two calls is the type of the closure and the `throws` flag. As such, the overload selection is sometimes ambiguous. Furthermore, due to the change of the pointer type, converting the contents of that pointer becomes more difficult than before in some cases.) If you don't care about those warnings, feel free to merge. Otherwise, please let me know. Thanks!

### CODE REVIEW

**Comment by apizz** [comment]
@wjk I'll leave it to you to decide.  The development of the app up until your commits today has been stalled, so if you feel these changes are best for the future development of the project, I have no problem merging so long as you plan on addressing the errors at some point.

**Comment by wjk** [comment]
@apizz I figured out how to fix the deprecation warnings. This PR is now good to go. Thanks!

**Comment by kevinmcox** [comment]
Nice!

**Comment by apizz** [comment]
Nice indeed! thank you

**Pull request merged**
