### PR TITLE
Update ProfileCreator 

### PR DESCRIPTION
**Pull request by WillYu91**
- Removed Sparkle, will use MAS for updates for now, will probably re-introduce it back in at a later time for Non-MAS distributions (Need to use the new swift package workflow)
- Moved ProfilePayloads and ProfileManifests to submodules
- Moved Highligtr framework to submodule to reduce code bloat from 3rd party framework
- Implemented profile settings preview
- Fixed toolbar icons to no longer use custom buttons and mouse area listeners, this was breaking per major OS version and was more trouble than it was worth compared to just using built in system APIs
- Squashed almost all warnings -> down to ~3 warnings
- Warnings that we can't squash are due to feature deprecations of the OS that we can't avoid, and swift does not provide a way to silence one particular instance of a warning (the others can be squashed by moving from using the `SecCertificate` API -> swift x509 API
- Set up XCode cloud building for CI -> Not sure how this will work in the main repo, I think it only works in mine
- System extension + Kernel extension policy support for editing bundles in the UI directly
- Fix issue with Microsoft opentype fonts
- Various UI fixes and alignments with text/checkboxes

### CODE REVIEW

**Comment by kevinmcox** [comment]
Will, thank you very much for all your work and submitting this here.

To be honest, with 886 files changes there is no way I'd be able to review, let alone likely understand, all the changes in this PR.

That said, I was able to successfully build the app following the instructions in the ReadMe (after opening the project in Xcode and removing the signing certificate I obviously don't have access to). It opened and ran fine, and the crashing issue with the SSO Extension is indeed fixed.

There are a few things I noticed that I think we need to get everyone in agreement on so we can move forward:

• The Bundle ID is changed. I personally think we should stick with the existing `com.github.ProfileCreator`
• Copyright. Would it make sense to have the copyright be © 2024 The ProfileCreator Project (or something similar)? This would mirror other open source projects like Munki.

Once we agree on those and any other issues I think it is time to take a leap of faith, merge this PR and cut a new release.

**Comment by WillYu91** [comment]
Yes those are all reasonable changes to ask for I'll go ahead and make them, thank you!

**Comment by WillYu91** [comment]
@kevinmcox I've updated the bundle ID and copyright

**Review by kevinmcox — APPROVED** [review]
Thanks for doing all this work!

**Comment by WillYu91** [comment]
Hey @kevinmcox I don't have merge permissions, someone with permissions will need to merge this PR 

image

**Comment by kevinmcox** [comment]
Thanks for the reminder @WillYu91. One thing I forgot to ask about is the Sparkle feed, I think we should keep that in the app and I'm not sure where the current commits stand.

**Comment by WillYu91** [comment]
@kevinmcox done here 022f420198ff58fca56e1f3069563cf2c4575dd5

**Comment by kevinmcox** [comment]
I left a comment on that last commit, the URL needs to be updated.

**Pull request merged**
